services:
  # 백엔드 서비스 설정
  backend:
    build:
      context: ./com.auditor
      dockerfile: Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./com.auditor:/app
      - /app/__pycache__
    env_file:
      - ./com.auditor/.env
    environment:
      OLLAMA_HOST: http://host.docker.internal:11434

  # 프론트엔드 서비스 설정
  frontend:
    build:
      context: ./watcher.www
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./watcher.www:/app
      - /app/.next
      - /app/node_modules
    env_file:
      - ./watcher.www/.env.local
    environment:
      BACKEND_URL: http://backend:8000
    depends_on:
      - backend

  # n8n 워크플로우 자동화
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    external: true
